### ISSUE TITLE
Why the c/a ratio is not ~1.6?

### ISSUE THREAD

**Issue by adengz** [materialsvirtuallab/nano266#2]
Ideally, it should be 1.633. The data in MP is ~1.6, no matter calculated or from ICSD. But why are we trying  near 1.73?

**Comment by shyuep** [comment]
There are slight differences in the type of pseudopotential used. This problem used the Ultrasoft PSP. MP uses PAW. Also, MP uses a relatively low $k$-point grid. 

The equilibrium c/a calculated should indeed be near 1.73.

**Comment by shyuep** [comment]
Also, what do you mean by "ideally". There is no "ideal" hcp c/a.

**Comment by adengz** [comment]
I see. That makes sense. 

1.633 is the c/a ratio from close packing hard sphere model. Just treat it as a reference...
